"""initial billing schema

Revision ID: 9ef121cee1c8
Revises:
Create Date: 2026-09-10 00:58:56.981576
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '9ef121cee1c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('total_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('commission_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'PAID', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_invoices_branch_id'), 'invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_invoices_employee_id'), 'invoices', ['employee_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('routing_key', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_invoices_employee_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_branch_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
    # create_table создаёт тип неявно, а drop_table его не удаляет:
    # без этого повторный upgrade падает на DuplicateObjectError.
    sa.Enum(name="invoice_status").drop(op.get_bind(), checkfirst=True)
